In [6]:
import numpy as np
from numpy.linalg import inv
a = np.array([[3., 2.,-1.], [2., -2.,4.],[-1., 0.5,-1.]])
ainv = inv(a)
ainv = inv(np.matrix(a))
ainv

matrix([[ 1.48029737e-16, -5.00000000e-01, -2.00000000e+00],
        [ 6.66666667e-01,  1.33333333e+00,  4.66666667e+00],
        [ 3.33333333e-01,  1.16666667e+00,  3.33333333e+00]])

In [7]:
A = np.array([[3., 2.,-1.], [2., -2.,4.],[-1., 0.5,-1.]])
print (A)
b = np.array([1.,-2.,0.])
print (b)

[[ 3.   2.  -1. ]
 [ 2.  -2.   4. ]
 [-1.   0.5 -1. ]]
[ 1. -2.  0.]


In [8]:
z = np.linalg.solve(A,b)
print (z)

[ 1. -2. -2.]
